#!/usr/bin/env php
<?php

if (file_exists(__DIR__.'/vendor/autoload.php')) {
    require __DIR__.'/vendor/autoload.php';
} else {
    require __DIR__.'/../../autoload.php';
}

$app = new Symfony\Component\Console\Application('Flare Installer', '0.2.0');
$app->add(new LaravelFlare\Install\Console\InstallCommand());
$app->run();
